from django.contrib import admin
from django.urls import path
from asosiy.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('jadval/',hamma_kitoblar),
    path('royhat/', hamma_mualliflar),
    path('talaba/',bitiruvchi_talaba),
    path('bitta_talaba/<int:aw>/',bitta_talaba),
    path('a_talaba/',a_talaba),
    path('tanlangan/<str:fr>/',tanlangan),
    path('tankitob/<int:rt>/',tan_kitob),
    path('record/', hamma_recordlar),
    path('tirik/',tirik_muallif),
    path('kitoblar/',sahifa_book),
    path('mualliflr/',mehnatkash),
    path('student/',hamma_talaba),
    path('asd/<int:pk>/',talaba_ochir),
    path('delete/<int:pk>/',kitob_ochir),
    path('sana3/',record_sana),
    path('kitoblife/', tirik_kitob),
    path('badiiykitob/',kitob_badiiy),
    path('muallif3/', katta_yosh),
    path('muallif10/', kitob_10),
    path('tanid/<int:jt>/',tan_id),
    path('kurs4/', Record_4),
    path('talabalar/', talabalar),
    path('talabalar/<int:id>/tahrirlash/',talaba_tahrirlash),
    path('royhat/<int:id>/tahrirlash/',muallif_tahrirlash),
    path('record/<int:id>/tahrirlash/',record_tahrirlash),
    path('kutub/', hamma_kutubhonachilar),
    path('lib/<int:id>/tahrirlash/', kutubhonachi_tahrirlash),
    path('mualliflar/',mualliflarr),
    path('kutubhonachilar/',kutubhonachilar),
    path('recordlar1/', recordlar1),

]
